name = "humanize"
version = "1.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Small Gleam helpers to make numbers, bytes, durations and lists human-friendly."
licences = ["MIT"]
repository = { type = "github", user = "lupodevelop", repo = "humanize" }
links = []
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_time = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
woof = ">= 1.0.1 and < 2.0.0"
